# Generated by Django 5.0.3 on 2024-06-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bd_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('mensaje', models.CharField(max_length=500, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
            },
        ),
    ]
